companyblog/blog_posts/forms.py
#puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title: ', validators=[DataRequired()])
    text = TextAreaField('Text: ', validators = [DataRequired()])
    submit = SubmitField('Post')

companyblog/blog_posts/views.py
# puppycompanyblog/blog_posts/views.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_required, current_user
from companyblog import db
from companyblog.models import BlogPost
from companyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

########### CRUD ############
# CREATE
@blog_posts.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(user_id = current_user.id, title = form.title.data, text = form.text.data)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created!')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

# Read (viewing a blog post)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title = blog_post.title, text = blog_post.text, date = blog_post.date, post = blog_post)

# Update
@blog_posts.route('/<int:blog_post_id>/update', methods = ['GET', 'POST'])
@login_required
def update(blog_post_id):
    # we will get the blog post from the database
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    # if the person opened the blog post to update is not the one who posted it, he cannot post it
    if blog_post.author != current_user:
        abort(403)

    # if the persion opened opened the post to edit is the one who posted it, he can edit
    form = BlogPostForm()
    # when he clicks submit, all the details will be updated
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id = blog_post_id))

    # before clicking update, he will see the old data prefilled in the input areas
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title = 'Updating', form = form)

# Delete
# @blog_posts.route('/<int:blog_post_id>/delete', methods = ['POST']) # didn't use methods = ['GET', 'POST']
# @login_required
# def delete_post(blog_post_id):
#     blog_post = BlogPost.query.get_or_404(blog_post_id)
#     if blog_post.author != current_user:
#         abort(403)
#     db.session.delete(blog_post)
#     db.session.commit()
#     flash('Blog Post Deleted')
#     return redirect(url_for('core.index'))

@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

companyblog/core/views.py
# core/views.py
from flask import render_template, request, Blueprint
from companyblog.models import BlogPost


core=Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type = int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

companyblog/users/views.py
# puppycompanyblog/users/views.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_required, login_user, current_user, logout_user

from companyblog import db
from companyblog.models import User, BlogPost
from companyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from companyblog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

# register
@users.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username = form.username.data, password = form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged In successfully!')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html', form = form)

# logout
@users.route('/logout')
# @login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account (UpdateUserForm)
@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:     # there is no DataRequired validator in the picture attribute. so this statement says, if the user provides any picture
            username = current_user.username          # grab the current_user's username
            pic = add_profile_pic(form.picture.data, username)        # saves the image including picture name in the database
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename = 'profile_pics/'+current_user.profile_image)

    return render_template('account.html', profile_image = profile_image, form=form)

# user's list of Blog posts
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type= int)
    user = User.query.filter_by(username= username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author= user).order_by(BlogPost.date.desc()).paginate(page=page, per_page= 5)        # User classes is related to BlogPost class with backref = author
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

companyblog/templates/account.html
{% extends 'base.html' %}
{% block content %}
<div align = 'center'>
  <h1>Welcome to the page for {{current_user.username|capitalize}}</h1>
  <img align='center'  class="img-thumbnail" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
  <p></p>
  <h2><span class="badge bg-secondary">{{ current_user.username|capitalize }}</span></h2>
</div>
<br>
<div class="container-fluid px-5">
  <div class="container-fluid px-5">
    <div class="container-fluid px-5">
      <div class="container-fluid px-5">
        <div class="container-fluid px-5">
          <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="mb-3">
              {{form.username.label(class= 'form-label')}} <br> {{form.username(class = 'form-control' )}}
            </div>
            <div class="mb-3">
              {{form.email.label(class= 'form-label')}} <br> {{form.email(class = 'form-control')}}
            </div>
            <div class="mb-3">
              {{form.picture.label(class= 'form-label')}} <br> {{form.picture(class = 'form-control')}}
            </div>
            <div class="mb-3">
              {{form.submit(class="btn btn-primary")}}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
    <!-- <form method="POST" action="" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="mb-3">
        {{form.username.label(class= 'form-label')}} <br> {{form.username(class = 'form-control')}}
      </div>
      <div class="mb-3">
        {{form.email.label(class= 'form-label')}} <br> {{form.email(class = 'form-control')}}
      </div>
      <div class="mb-3">
        {{form.picture.label(class= 'form-label')}} <br> {{form.picture(class = 'form-control')}}
      </div>
      <div class="mb-3">
        {{form.submit(class="btn btn-primary")}}
      </div>
    </form> -->

{% endblock %}

companyblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Company Blog</title>
  </head>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  <body class = "bg-dark" style="--bs-bg-opacity: .9;" >
    <ul class = 'nav nav-dark bg-dark'>
      <li class = 'nav-link'><a href="{{url_for('core.index')}}"  style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Home</a></li>
      <!-- 'core.index' because we are referring that file using 'core' blueprint -->
      <li class = 'nav-link'><a href="{{url_for('core.info')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">About</a></li>

      {% if current_user.is_authenticated %}

      <li class = 'nav-link'><a  href="{{url_for('users.account')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Account</a></li>
      <li class = 'nav-link'><a href="{{url_for('blog_posts.create_post')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Create Post</a></li>
      <li class = 'nav-link'><a href="{{url_for('users.logout')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Log Out</a></li>
      {% else %}
      <li class = 'nav-link'><a href="{{url_for('users.register')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Register</a></li>
      <li class = 'nav-link'><a href="{{url_for('users.login')}}" style="text-decoration:none" class="fw-bold bg-danger badge fs-6">Log In</a></li>
      {% endif %}
    </ul>
    <div class="container-fluid">
      <p></p>
      <div class="container-fluid bg-dark text-light p-5">
      {% block content %}

      {% endblock %}
      </div>
    </div>
  </body>
</html>

companyblog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid bg-light text-dark p-5">
  <h1>{{title}}</h1>
  <h3>Written by: {{post.author.username}}</h3>
  <h4>Published: {{date.strftime("%M %d, %Y")}}</h4>
  <p>{{text}}</p>
  {% if post.author==current_user %}
  <div>
    <a class="btn btn-secondary" href="{{url_for('blog_posts.update', blog_post_id=post.id)}}">Update</a>
    <button type="button" class='btn btn-danger' data-bs-toggle='modal' data-bs-target="#del_modal" >Delete</button>
  </div>
  {% endif %}
</div>

  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark">Delete Post?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="text-dark">Are you sure you want to delete the post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary text-dark" data-bs-dismiss="modal">Cancel</button>
          <form class="" action="{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}" method="POST">
            <input class='btn btn-danger' type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

companyblog/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<form class="form-group" method="POST">
  {{form.hidden_tag()}}
  <div class="form-group">
    {{form.title.label(class='form-control-label')}} <br>{{form.title(class='form-control form-control-lg')}}
  </div>
  <br>
  <div class="form-group">
    {{form.text.label(class='form-control-label')}} <br>{{form.text(class = 'form-control form-control-lg')}}
  </div>
  <br>
  <div class="form-group">
    {{form.submit(class='btn btn-outline-info')}}
  </div>
</form>
{% endblock %}

companyblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class = 'text-center'>Company Blog</h1>
    <br>
    <div class="container">
      {% for post in blog_posts.items %}
      <div class="card">
        <div class="card-body">
          <h2 class="card-title"><a class="text-dark" style="text-decoration:none" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
          <a class="text-dark" style="text-decoration:none" href="{{url_for('users.user_posts', username=post.author.username)}}">Written by: {{post.author.username}}</a>
          <p class="text-dark">Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
          <p class="card-text"><a class="text-dark" style="text-decoration:none" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.text}}</a></p>
          <a class='btn btn-primary' href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">Read Blog Post</a>
        </div>
      </div>
      <br>
      {% endfor %}
    </div>
    <br><br><br>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current = 2) %}
          {% if blog_posts.page==page_num %}
            <li class='page-item disabled'><a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>
          {% else %}
            <li class='page-item'><a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>

{% endblock %}

companyblog/templates/info.html
{% extends 'base.html' %}
{% block content %}
  <h1>Information about our Company</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

companyblog/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
  <div class="mb-3">
    {{form.email.label(class= 'form-label')}} <br> {{form.email(class = 'form-control')}}<br>
  </div>
  <div class="mb-3">
    {{form.password.label(class= 'form-label')}} <br> {{form.password(class="form-control")}}<br>
  </div>
    {{form.submit(class="btn btn-primary")}}
</form>
{% endblock %}

companyblog/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
  <div class="mb-3">
    {{form.email.label(class= 'form-label')}} <br> {{form.email(class = 'form-control')}}<br>
  </div>
  <div class="mb-3">
    {{form.username.label(class= 'form-label')}} <br> {{form.username(class="form-control")}}<br>
  </div>
  <div class="mb-3">
    {{form.password.label(class= 'form-label')}} <br> {{form.password(class="form-control")}}<br>
  </div>
  <div class="mb-3">
    {{form.pass_confirm.label(class= 'form-label')}} <br> {{form.pass_confirm(class="form-control")}}<br>
  </div>
    {{form.submit(class="btn btn-primary")}}
</form>
{% endblock %}

companyblog/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}
<div align='center' class = 'container-fluid'>
  <h1>Welcome to the page for {{user.username}}</h1>
  <img align='center' class="img-thumbnail" src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}">
  <br> <br>
</div>
<div class="container-fluid">
  {% for post in blog_posts.items %}
  <div class="container-fluid bg-light text-dark p-3 rounded">
    <h2><a class="text-dark" style="text-decoration:none" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
    Written By: <a class="text-dark" style="text-decoration:none" href="{{url_for('users.user_posts', username = post.author.username)}}">{{post.author.username}}</a>
    <p class="text-dark" style="text-decoration:none" class='text-muted'>Published On: {{post.date.strftime("%Y-%m-%d")}}</p>
    <p class="text-dark" style="text-decoration:none" >{{post.text}}</p>
  </div>
    <br>
  {% endfor %}
  <br>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current = 2) %}
      {% if blog_posts.page==page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li>
      {% else %}
        <li class='page-item'><a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}